### ISSUE TITLE
Wrong Board selected in Arduino

### ISSUE THREAD

**Issue by LeSuedois** [khoih-prog/RPI_PICO_TimerInterrupt#1]
Hello,
I tried to use your library but even the examples don't compile. It says the wrong board is selected..
I use Arduino 1.8.19 on os x 12.2.1, core and library with arduino library manager, all up to date.
RPi pico is selected in the board manager and I use RP2040 since a while with success.
`/Users/simonjuif/Documents/Arduino/libraries/MBED_RPI_PICO_TimerInterrupt/src/MBED_RPi_Pico_TimerInterrupt.hpp:47:4: error: #error This code is intended to run on the MBED RASPBERRY_PI_PICO platform! Please check your Tools->Board setting.
   47 |   #error This code is intended to run on the MBED RASPBERRY_PI_PICO platform! Please check your Tools->Board setting.
      |    ^~~~~
exit status 1`

Thank you,
Simon

**Comment by khoih-prog** [comment]
Hi,

With the **careless** post to the **wrong** library, you'd have more problem in the future, especially while using hardware interrupt. Be much more careful in the future.

```
#error This code is intended to run on the MBED RASPBERRY_PI_PICO platform! Please check your Tools->Board setting
```

The `MBED_RPI_PICO_TimerInterrupt` is designed for RP2040 using [**ArduinoCore-mbed** core](https://github.com/arduino/ArduinoCore-mbed)

While this library is designed for [**arduino-pico** core](https://github.com/earlephilhower/arduino-pico)

Retry using the correct core for the library by at least reading [**Prerequisites**](https://github.com/khoih-prog/RPI_PICO_TimerInterrupt#prerequisites).

Good Luck,
