### ISSUE TITLE
Measure RPM example for Arduino MBED core

### ISSUE THREAD

**Issue by w9ran** [khoih-prog/RPI_PICO_TimerInterrupt#4]
Hello!
Thank you for what looks like an excellent Timer Interrupt library for the Pi Pico, as I've been unable to master the use of the SDK functions.   I hope you might be able to help me learn to apply it for my application of measuring audio frequency tones as I may not be able to create it at my present skill level.    

While studying the examples I found "RPM Measure" on Github:
https://github.com/khoih-prog/RPI_PICO_TimerInterrupt/tree/main/examples/RPM_Measure

But, it was written for the Earle Philhower Pico board support, and I'd prefer to stay with the Arduino MBED Core if possible.   I was pleased to find your library now supports MBED but am having trouble translating the RPM Measure  example to the MBED library.   Would it be possible to get a version that runs under Arduino MBED core?

I've resolved some compilation errors but simply adding "MBED_" to the function name, but am presently stuck with this error at line 135:  
invalid conversion from 'bool (*)(repeating_timer*)' to 'hardware_alarm_callback_t {aka void (*)(unsigned int)}' [-fpermissive]

Any assistance would be much appreciated!   Thanks again for creating this great library for the Pico, which is much needed.
Bob

**Comment by khoih-prog** [comment]
HI @w9ran 

As this is not an issue of this library, I'm closing it now to avoid unnecessary confusion.

I suggest you post on [**Discussions**](https://github.com/khoih-prog/MBED_RPI_PICO_TimerInterrupt/discussions) section of that [**MBED_RPI_PICO_TimerInterrupt** library](https://github.com/khoih-prog/MBED_RPI_PICO_TimerInterrupt), hopefully someone will help you out, as I don't have enough time to deal with your porting issue. YOu can also post on Arduino Forum to ask for help from many experts there. Just remember to follow the rule and include [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example)

Good Luck,
